
name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  version: develop
  tmpfolder: tmp-folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check tmp folder
        shell: bash
        run: |
          if [ -d $tmpfolder ]; then
            echo "temp folder $tmpfolder must not exist";
            exit 1;
          fi;
      - name: get templates
        shell: bash
        run: |
          git clone --depth 1 --branch ${{env.version}}  https://$GITHUB_ACTOR:$TOKEN@$REPO $tmpfolder
        env: 
          TOKEN: ${{secrets.WORKFLOW_PAT}}
          REPO: ${{secrets.MAVEN_IMAGE_WORKFLOW_REPO}}
          
      - name: copy templates
        shell: bash
        run: |
          mkdir tmp
          cp $tmpfolder/templates/* tmp
          rm -rf $tmpfolder
          echo ${{ fromJSON('{"message": toJSON(github.event.head_commit.message)}') }}
          
      - name: list templates
        run: ls -alR . 
