
name: CI

on:
  workflow_dispatch:

env:
  version: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get templates
        run: |
          git clone --depth 1 --branch ${{env.version}}  https://$GITHUB_ACTOR:$TOKEN@$REPO
        env: 
          TOKEN: ${{secrets.WORKFLOW_PAT}}
          REPO: ${{secrets.MAVEN_IMAGE_WORKFLOW_REPO}}
          
      - name: copy templates
        run: |
          mkdir tmp
          cp maven-image-workflow-generator/templates/* tmp
          
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
