
name: CI

on:
  workflow_dispatch:

env:
  version: develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          git clone --depth 1 --branch ${{env.version}}  https://$GITHUB_ACTOR:$GH_TOKEN@github.com/dvag/maven-image-workflow-generator.git
          cp -R templates/ tmp
        env: 
          GH_TOKEN: ${{secrets.WORKFLOW_PAT}}
          
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
