
name: CI

on:
  workflow_dispatch:
    input:
      target_folder:
        description: 'the folder the templates are copied to'
        required: true
        default: 'templates'
      tmp_folder:
        description: 'a temporary folder used for internal processing, must not exist'
        required: true
        default: 'tmp_work'

env:
  version: develop
  tmpfolder: xxx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check tmp folder
      shell: bash
      run:
        if [ -d ${{ github.event.input.tmp_folder }} ]; then
        echo "output folder ${{ input.tmp_folder }} must not exist";
        exit 1;
        fi;
    - name: get template
      shell: bash
      run: 
        git clone --depth 1 --branch ${{env.version}}  https://$GITHUB_ACTOR:$TOKEN@$REPO ${{ github.event.input.tmp_folder }}
      env:
        TOKEN: ${{ secrets.WORKFLOW_PAT }}
        REPO: dvag/maven-image-workflow-generator

    - name: copy templates
      shell: bash
      run: |
        mkdir ${{ github.event.input.target_folder }}
        cp ${{ github.event.input.tmp_folder }}/templates/* ${{ github.event.input.target_folder }}
        rm -rf ${{ github.event.input.tmp_folder }}
        ls -alR .
