
name: CI

on:
  workflow_dispatch:
    inputs:
      target_folder:
        description: 'the folder the templates are copied to'
        required: true
        default: 'templates'
      tmp_folder:
        description: 'a temporary folder used for internal processing, must not exist'
        required: true
        default: 'tmp_work'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check target_folder folder
      shell: bash
      run:
        if [ -d ${{ github.event.inputs.target_folder }} ]; then
        echo "output folder ${{ github.event.inputs.target_folder }} must not exist";
        exit 1;
        fi;
    - name: check tmp_folder folder
      shell: bash
      run:
        if [ -d ${{ github.event.inputs.tmp_folder }} ]; then
        echo "output folder ${{ github.event.inputs.tmp_folder }} must not exist";
        exit 1;
        fi;
    - name: get template
      shell: bash
      run: 
        git clone --depth 1 --branch $REPO_VERSION  https://$GITHUB_ACTOR:$TOKEN@github.com/$REPO ${{github.event.inputs.tmp_folder}} 
      env:
        TOKEN: ${{ secrets.WORKFLOW_PAT }}
        REPO: dvag/maven-image-workflow-generator
        REPO_VERSION: v0.0.3

